### ISSUE TITLE
Protocol not available

### ISSUE THREAD

**Issue by ne-vlezay80** [troglobit/pim6sd#25]
Runneng with archlinux:
```
pim6sd: 18:53:33.417 warning - setsockopt(IPV6_ROUTER_ALERT): Protocol not available
```
Kernel: 5.4.24-rt15-2-rt

**Comment by troglobit** [comment]
Well, have you checked your kernel config, do you have everything related to IPv6 enabled?

**Comment by tycho** [comment]
I just ran into this too. It looks like the kernel doesn't like the socket protocol?

```c
    /* RA packet may be delivered ONLY to IPPROTO_RAW socket */
    if (sk->sk_type != SOCK_RAW || inet_sk(sk)->inet_num != IPPROTO_RAW)
        return -ENOPROTOOPT;
```

`mld6_socket` is created with `IPPROTO_ICMPV6`:
```c
     if ((mld6_socket = socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6)) < 0)
```

**Comment by troglobit** [comment]
Yup, seems you're right.  Linux doesn't support the IPV6_ROUTER_ALERT socket option, as far as I can see -> https://code.woboq.org/linux/linux/net/ipv6/raw.c.html#do_rawv6_setsockopt

I haven't checked, but I'm guessing this works on *BSD, likely originating from the KAME project.  So this code, like much else in this restoration project, needs porting to Linux.  Any and all help is appreciated! :-)

**Comment by troglobit** [comment]
Warning removed in 6a07b6b.  Reasoning inline in code:

> On Linux the `IPV6_ROUTER_ALERT` option can only be modified if the `socket()` was created
> with `SOCK_RAW` and `IPPROTO_RAW`, i.e., on Linux this `setsockopt()` call will fail.
