### ISSUE TITLE
Potentially broken PIM checksum

### ISSUE THREAD

**Issue by T-X** [troglobit/pim6sd#7]
We've seen PIM messages in Wireshark with a broken checksum.

My ones from fe80::2 were fine while @mweinelt was sending bogus ones from fe80::1. One difference was that I had deleted the auto-generated link-local address on my ip6gre1 interface while @mweinelt hadn't. After he deleted that one, too, the checksum was fine again.

My guess is that pim6sd had chosen to the auto-generated IPv6 link-local address for its checksum computation. But the packets were then send with the fe80::1/64 he had manually assigned.

One key difference with PIM in IPv6 compared to IPv4 I think is that that the checksum is calculated over this "IPv6 pseudo header" which includes the IPv6 source and destination address.

**Comment by troglobit** [comment]
Interesting! I'll see what I can find, step one is to reproduce it. Can also check with xorp pimd to see what they do.

**Comment by T-X** [comment]
Here is a script to reproduce the checksum issues:

https://gist.github.com/T-X/9b689b185c72607ab325a275868e01bb

Which creates this setup:

<pre><code>[NS:client0] <---> [NS:router0] <---> [NS:router1] <---> [NS:client1]</code></pre>

Here, router0 will send PIM messages with a broken checksum to router1 as can be observed via tcpdump:

<pre><code>$ ip netns exec pimtest-router1 tcpdump -l -n -v -i wan0 pim
tcpdump: listening on wan0, link-type EN10MB (Ethernet), capture size 262144 bytes
20:33:58.537463 IP6 (flowlabel 0x13151, hlim 1, next-header PIM (103) payload length: 72) fe80::1 > ff02::d: PIMv2, length 72
        Bootstrap, cksum 0xd8cc (incorrect) tag=5b8 hashmlen=126 BSRprio=0 BSR=fd5c:725:2841::1 (group0: ff00::/8 RPcnt=1 FRPcnt=1 RP0=fd5c:725:2841::1,holdtime=2m30s,prio=0)
20:34:18.552348 IP6 (flowlabel 0x5b502, hlim 1, next-header PIM (103) payload length: 70) fe80::11:22ff:fe00:2 > ff02::d: PIMv2, length 70
        Hello, cksum 0xa47e (correct)
          Hold Time Option (1), length 2, Value: 1m45s
          DR Priority Option (19), length 4, Value: 1
          Generation ID Option (20), length 4, Value: 0x34658b7e
          Address List Option (24), length 18, Value: 
          Address List (Old) Option (65001), length 18, Value: 
20:34:18.552509 IP6 (flowlabel 0x13151, hlim 1, next-header PIM (103) payload length: 106) fe80::1 > ff02::d: PIMv2, length 106
        Hello, cksum 0xa335 (incorrect)
          Hold Time Option (1), length 2, Value: 1m45s
          DR Priority Option (19), length 4, Value: 1
          Generation ID Option (20), length 4, Value: 0x34658b7e
          Address List Option (24), length 36, Value: 
          Address List (Old) Option (65001), length 36, Value: 
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel
</code></pre>

**Comment by T-X** [comment]
Ok, I have a working solution for this. Give me a minute, I'll make a pull-request.
