### ISSUE TITLE
RP-Set not refreshing / vanishing PIM bootstrap

### ISSUE THREAD

**Issue by T-X** [troglobit/pim6sd#8]
When I initially start pim6sd and receive a PIM bootstrap message (or via a PIM Hello option?), the RP-Set is populated just fine:

<pre><code>01:55:06.111 no group_prefix was specified
01:55:06.111 Local BSR address: fd5c:725:2841::2
01:55:06.111 Local BSR priority : 0
01:55:06.111 Local BSR period is : 0 sec.
01:55:06.112 Local BSR hash mask length: 0
01:55:06.162 skip the existing address
---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 155
RP-address(Upstream)/Group prefix             Prio Hold Age
fd5c:725:2841::1(fe80::1%ip6gre1)
     ff00::/8                                 0    150  145
</code></pre>

However when receiving the next bootstrap message, pim6sd reports some issues:

<pre><code>01:56:00.468 NETLINK: ask path to fd5c:725:2841::1
01:56:00.468 warning - NETLINK: ifindex=4, but no vif
01:56:00.468 receive_pim6_bootstrap: can't find a route to the BSR(fd5c:725:2841::1)
</code></pre>

Trying to ping this IPv6 Unique Local Address works just fine though:

<pre><code>$ ping6 fd5c:725:2841::1
PING fd5c:725:2841::1(fd5c:725:2841::1) 56 data bytes
64 bytes from fd5c:725:2841::1: icmp_seq=1 ttl=64 time=165 ms
64 bytes from fd5c:725:2841::1: icmp_seq=2 ttl=64 time=184 ms
^C
--- fd5c:725:2841::1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 3ms
rtt min/avg/max/mdev = 164.666/174.281/183.896/9.615 ms
</code></pre>

Eventually the RP-Set entries time out and the "Current BSR address" is replaced by the zero/unspecified IPv6 address and stays that way even when the next PIM bootstrap message is received:

<pre><code>---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 5
RP-address(Upstream)/Group prefix             Prio Hold Age

01:57:45.419 nothing to do with general-query on router-side, except for querier-election
---------------------------RP-Set----------------------------
Current BSR address: :: Prio: 0 Timeout: 160
RP-address(Upstream)/Group prefix             Prio Hold Age

---------------------------RP-Set----------------------------
Current BSR address: :: Prio: 0 Timeout: 155
RP-address(Upstream)/Group prefix             Prio Hold Age

---------------------------RP-Set----------------------------
Current BSR address: :: Prio: 0 Timeout: 150
RP-address(Upstream)/Group prefix             Prio Hold Age

01:58:00.213 NETLINK: ask path to fd5c:725:2841::1
01:58:00.213 warning - NETLINK: ifindex=4, but no vif
01:58:00.213 receive_pim6_bootstrap: can't find a route to the BSR(fd5c:725:2841::1)
---------------------------RP-Set----------------------------
Current BSR address: :: Prio: 0 Timeout: 145
RP-address(Upstream)/Group prefix             Prio Hold Age

01:58:05.742 skip the existing address
</code></pre>

The two interfaces configured in pim6sd.conf look like this:

<pre><code>134: ip6gre1@NONE: (POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP) mtu 1448 qdisc noqueue state UNKNOWN group default qlen 1000
    link/gre6 2001:67c:2d50:0:7e76:35ff:fe14:e6d7 peer 2001:67c:2ed8:0:217:f2ff:fe93:66c9
    inet6 fd5c:725:2841::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::2/64 scope link 
       valid_lft forever preferred_lft forever
142: pim-veth0@if141: (BROADCAST,MULTICAST,UP,LOWER_UP) mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ae:0d:96:7b:5f:b1 brd ff:ff:ff:ff:ff:ff link-netns pim6test0
    inet6 fe80::ac0d:96ff:fe7b:5fb1/64 scope link 
       valid_lft forever preferred_lft forever
</code></pre>

And the bootstrap router (fd5c:725:2841::1) is behind ip6gre1.

The "ifindex=4" in the NETLINK warning looks a bit suspicious. That is the ifindex of my main/wireless interface "wlp61s0". Which has the default routes and provides internet connectivity etc.

**Comment by T-X** [comment]
When hard-coding the ifindex to the one from ip6gre1 (the interface the PIM bootstrap message was received on) like this:

<pre><code>$ git diff
diff --git a/src/netlink.c b/src/netlink.c
index a1b2f1c..5d4fbd9 100644
--- a/src/netlink.c
+++ b/src/netlink.c
@@ -214,7 +214,7 @@ getmsg(struct rtmsg *rtm, int msglen, struct rpfctl *rpf)
     parse_rtattr(rta, RTA_MAX, RTM_RTA(rtm), msglen - sizeof(*rtm));
     
     if (rta[RTA_OIF]) {
-       int ifindex = *(int *) RTA_DATA(rta[RTA_OIF]);
+       int ifindex = 134;
        
        for (vifi = 0, v = uvifs; vifi < numvifs; ++vifi, ++v) {
</code></pre>

Then the RP-Set is refreshed successfully:

<pre><code>---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 100
RP-address(Upstream)/Group prefix             Prio Hold Age
fd5c:725:2841::1(fe80::1%ip6gre1)
     ff00::/8                                 0    150  90

02:44:00.280 NETLINK: ask path to fd5c:725:2841::1
02:44:00.280 NETLINK: vif 0, ifindex=134
02:44:00.280 NETLINK: gateway is fe80::5054:ff:fe0c:bbeb
---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 155
RP-address(Upstream)/Group prefix             Prio Hold Age
fd5c:725:2841::1(fe80::1%ip6gre1)
     ff00::/8                                 0    150  145
</code></pre>

**Comment by troglobit** [comment]
That looks really odd, can't say I fully understand your setup, but I think I may have a similar problem in my limited setup with [CORE](https://www.nrl.navy.mil/itd/ncs/products/core).  If you run a simple one-router setup I can get it to work¹, but with a simple three-routers-in-a-row I cannot ... and I also see the loss of BSR on the edge routers.

I'm trying out different setup right now and will continue debugging from my end. Hopefully it's the same root cause.
____
¹ I have to add the following two lines from pim6sd.conf(5)
cand_bootstrap_router;
cand_rp;

**Comment by T-X** [comment]
Here's a script which should reproduce the problem within network namespaces:

https://gist.github.com/T-X/a1352078c24f5419c4566f0290f58dde

It's a simple two router setup, each of them has their own network namespace. And they each have one network namespace attached to them for downstream hosts:

<pre>[NS:client0] <---> [NS:router0] <---> [NS:router1] <---> [NS:client1]</pre>

As you can see in the pimtest-router1.log the BSR is first added correctly but later times out and in between the bootstrap messages get rejected.

The output is slightly different, but seems like the same issue:

<pre><code>19:17:28.578 NETLINK: ask path to fd5c:725:2841::1
19:17:28.578 warning - netlink get_route: Network is unreachable
19:17:28.579 receive_pim6_bootstrap: can't find a route to the BSR(fd5c:725:2841::1)
</code></pre>

It's maybe a PIM specific thing (still learning / reading about it), but I'm confused that pim6sd tries to retrieve a unicast route to the BSR in userspace. Shouldn't that be something the kernel should just do?

**Comment by T-X** [comment]
And adding a default route to the end of _setup()_ in the pimtest-bootstrap.sh makes things work:

<pre><code>$NSR1 ip -6 route add default dev wan0</code></pre>

=>

<pre><code>---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 120
RP-address(Upstream)/Group prefix             Prio Hold Age
fd5c:725:2841::1(fe80::5ca2:fff:feee:be08%wan0)
     ff00::/8                                 0    150  110

20:05:22.359 NETLINK: ask path to fd5c:725:2841::1
20:05:22.359 NETLINK: vif 0, ifindex=4
---------------------------RP-Set----------------------------
Current BSR address: fd5c:725:2841::1 Prio: 0 Timeout: 155
RP-address(Upstream)/Group prefix             Prio Hold Age
fd5c:725:2841::1(fe80::5ca2:fff:feee:be08%wan0)
     ff00::/8                                 0    150  145
</code></pre>

However I believe that should not be necessary. Especially as the interface with the default route might be an interface which was not added to / was disabled for pim6sd.

**Comment by troglobit** [comment]
Awesome, thanks for the script that will come in handy!  I believe CORE also uses namespaces to set things up, only using a GUI.  It's really handy since it can start up OSPFv3 and other things if you want.

Anyway, I get the same type of netlink error/warning in my setup (same topology).  From what I can gather it seems the code in `netlink.c` fails to query the IPv6 unicast routing table for the route to the neighbor in the BSR message, what seems to be failing is actually retrieving the gateway for the route, which makes the code fall back to return the source address.  The pimd code seems to require this to figure out which neighbor (found via HELLO) to associate with the BSR.  

So yeah, you should definitely not need to set up default routes.

**Comment by T-X** [comment]
Ok, found the issue: The code tries to copy the 16 bytes IPv6 address from a ``struct sockaddr_in6``. However it should be copied from the ``struct in6_addr sin6_addr`` within the sockaddr_in6. Otherwise it's off by the size of ``sin6_``, ``sin6_port`` and ``sin6_flowinfo``.

When I change that then it returns the ifindex of the correct interface, ip6gre1! \o/ And no more vanishing bootstrap router in the PR-Set.

I'll clean up my debugging mess and make a pull-request in a minute.

**Comment by troglobit** [comment]
What you found it?! Man, you're like a relentless bloodhound ... I was just going to bed, but now I have to see what you've come up with :-)

**Comment by troglobit** [comment]
Wow, yeah I see now! Suddenly my setup with two-routers works perfectly \o/

**Comment by T-X** [comment]
Exactly this :smile:. I've changed the passed parameter in my PR (I usually prefer just using pointers when the thing passed is larger than the word size), but change as you please :-).

**Comment by T-X** [comment]
And yaiy, great that this works for you too! :tada:

**Comment by troglobit** [comment]
Yeah, calling conventions are important.  I've started doing some cleanup of the code base to both simplify it and make it more readable.  First was to make it compile, this current step was to make it work, the next step is to build with different compilers, cross-compile and then unleash Coverity Scan on it.  It's slowly coming along :-)

Thank you again for your work and patience, both you and @mweinelt !
